// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mobxdcedtckzvusazdjg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1vYnhkY2VkdGNrenZ1c2F6ZGpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ3MzExMzgsImV4cCI6MjA5MDMwNzEzOH0.rlPEvd8zCstQea4dP07QgIcupG539qRyeU-5i9IW2MY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});